version: '3.8'
services:
  mps-cron:
    container_name: "etd-cron"
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ./data:/home/etdadm/data
      - ./logs:/home/etdadm/logs
    env_file:
      - ./.env
    environment:
      QUEUE_NAME: etd_submission_ready

# Create a custom docker network if it does not exist already
networks:
  etd-net:
    name: etd-net